import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useLocation} from 'react-router-dom';
import {LayoutDashboard,BriefcaseBusiness,BrainCircuit,UserRound,FolderKanban,UsersRound,Bell,BookOpen,LogOut,Plus,Search,Target,ChevronRight,Sparkles,GraduationCap,ShieldCheck,Menu,X,Send,CheckCircle2,BarChart3,FileText,LayoutTemplate,ExternalLink,Bookmark,Video,Award,Mail,Download,Eye,Palette,Globe,Check,PlayCircle,SearchCode} from 'lucide-react';
import './styles.css';
const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000/api';
async function api(path,opt={}){const token=localStorage.getItem('token'); const headers={'Content-Type':'application/json',...(opt.headers||{})}; if(token)headers.Authorization=`Bearer ${token}`; const r=await fetch(API+path,{...opt,headers}); if(!r.ok){let e={};try{e=await r.json()}catch{};throw new Error(e.detail||'Request failed')} return r.json()}
const demo={STUDENT:['student@example.com','password123'],INDUSTRY:['industry@example.com','password123'],ADMIN:['admin@example.com','password123']};
function App(){const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('user')||'null')); const [login,setLogin]=useState(!localStorage.getItem('token')); const [refresh,setRefresh]=useState(0); useEffect(()=>{const ripple=e=>{const el=document.createElement('span');el.className='clickRipple';el.style.left=`${e.clientX}px`;el.style.top=`${e.clientY}px`;document.body.appendChild(el);setTimeout(()=>el.remove(),650)};document.addEventListener('pointerdown',ripple);return()=>document.removeEventListener('pointerdown',ripple)},[]); if(login)return <Login onLogin={u=>{setUser(u);setLogin(false)}}/>; return <Shell user={user} setUser={setUser} refresh={refresh} bump={()=>setRefresh(x=>x+1)}/>}
function Login({onLogin}){const [mode,setMode]=useState('STUDENT');const [email,setEmail]=useState(demo.STUDENT[0]);const [password,setPassword]=useState(demo.STUDENT[1]);const [name,setName]=useState('');const [err,setErr]=useState('');async function go(){try{const data=mode==='REGISTER'?await api('/auth/register',{method:'POST',body:JSON.stringify({name,email,password,role:'STUDENT'})}):await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('token',data.token);localStorage.setItem('user',JSON.stringify(data.user));onLogin(data.user)}catch(e){setErr(e.message)}}return <div className="loginPage"><div className="orb o1"/><div className="orb o2"/><div className="loginCard"><div className="brand"><div className="brandIcon"><Sparkles/></div><div><b>Unique Path</b><span>AI Career Hub</span></div></div><div className="loginHero"><div className="eyebrow">AI-POWERED CAREER OPERATING SYSTEM</div><h1>Build your next <span>career chapter.</span></h1><p>Skills, assessments, opportunities, portfolio, mentors and an AI copilot — in one place.</p></div><div className="modeRow">{['STUDENT','INDUSTRY','ADMIN','REGISTER'].map(m=><button className={mode===m?'active':''} onClick={()=>{setMode(m);if(demo[m]){setEmail(demo[m][0]);setPassword(demo[m][1])}}}>{m}</button>)}</div>{mode==='REGISTER'&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/>}<input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{err&&<div className="error">{err}</div>}<button className="primary big" onClick={go}>{mode==='REGISTER'?'Create account':'Enter workspace'} <ChevronRight size={18}/></button><div className="demo">Demo passwords: <b>password123</b></div><div className="creatorBadge">Created by <b>Umera Sulthana</b></div></div></div>}
function Shell({user,setUser,refresh,bump}){const [page,setPage]=useState('Dashboard');const [mobile,setMobile]=useState(false);const nav=[['Dashboard',LayoutDashboard],['Career AI',BrainCircuit],['Jobs',BriefcaseBusiness],['Internships',GraduationCap],['Assessments',Target],['Skills',BarChart3],['Resume',FileText],['Portfolio',FolderKanban],['Learning',BookOpen],['ATS Score',SearchCode],['Mentors',UsersRound],['Career Tools',LayoutTemplate],['Profile',UserRound]]; if(user.role!=='STUDENT')nav.splice(5,0,['Applications',CheckCircle2]); if(user.role==='ADMIN')nav.push(['Admin',ShieldCheck]); return <div className="app"><aside className={mobile?'open':''}><div className="sideBrand"><div className="brandIcon"><Sparkles/></div><div><b>Unique Path</b><small>{user.role} workspace</small></div><button className="icon mobileClose" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([n,I])=><button className={page===n?'selected':''} onClick={()=>{setPage(n);setMobile(false)}}><I size={18}/>{n}</button>)}</nav><div className="sideBottom"><div className="verified"><ShieldCheck size={18}/><div><b>Profile verified</b><span>Career profile is active</span></div></div><button className="logout" onClick={()=>{localStorage.clear();setUser(null)}}><LogOut size={16}/> Sign out</button><div className="creatorSide">Created by <b>Umera Sulthana</b></div></div></aside><main><header><button className="icon menu" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb">Workspace <ChevronRight size={15}/>{page}</div><div className="headerRight"><span className="pulse">● AI online</span><button className="icon"><Bell size={19}/></button><div className="avatar">{user.name?.[0]}</div></div></header><section className="content">{page==='Dashboard'&&<Dashboard user={user} go={setPage} refresh={refresh}/>} {page==='Career AI'&&<CareerAI/>}{page==='Jobs'&&<ExternalJobs user={user} bump={bump}/>} {page==='Internships'&&<ExternalInternships user={user} bump={bump}/>} {page==='Opportunities'&&<Opportunities user={user} bump={bump}/>} {page==='Assessments'&&<Assessments bump={bump}/>} {page==='Skills'&&<Skills/>}{page==='Resume'&&<ResumeBuilder user={user}/>} {page==='Portfolio'&&<Portfolio bump={bump}/>} {page==='Learning'&&<Learning/>}{page==='ATS Score'&&<ATSScore/>}{page==='Mentors'&&<Mentors/>}{page==='Career Tools'&&<CareerTools user={user}/>} {page==='Profile'&&<Profile user={user} setUser={setUser}/>} {page==='Applications'&&<Applications/>}{page==='Admin'&&<Admin/>}</section></main></div>}
function Dashboard({user,go,refresh}){const [stats,setStats]=useState({});const [apps,setApps]=useState([]);const [gaps,setGaps]=useState([]);useEffect(()=>{api('/analytics').then(setStats);api('/applications').then(setApps).catch(()=>{});api('/skill-gap').then(setGaps).catch(()=>{})},[refresh]);return <><div className="hero"><div><div className="eyebrow">{user.role} · CAREER INTELLIGENCE</div><h2>Good evening, <span>{user.name}</span> 👋</h2><p>Your career workspace is ready. Turn signals into your next opportunity.</p><div className="actions"><button className="primary" onClick={()=>go('Career AI')}><Sparkles size={17}/> Ask Career AI</button><button className="ghost" onClick={()=>go('Opportunities')}>Explore opportunities</button></div></div><div className="heroGraphic"><div className="ring r1"/><div className="ring r2"/><Sparkles size={52}/></div></div><div className="statGrid">{[['Open roles',stats.opportunities||0,'↗'],['Applications',stats.applications||0,'◷'],['Skills tracked',stats.skills||0,'✦'],['Assessments',stats.assessments||0,'✓']].map(x=><div className="stat"><span>{x[2]}</span><b>{x[1]}</b><small>{x[0]}</small></div>)}</div><div className="grid2"><div className="panel"><div className="panelHead"><div><h3>Skill-gap radar</h3><p>Highest-impact skills for current opportunities</p></div><button className="textBtn" onClick={()=>go('Skills')}>View all</button></div>{gaps.slice(0,5).map(g=><div className="gapRow"><div><b>{g.skill}</b><span>Level {g.current}/4 → {g.target}/4</span></div><div className="bar"><i style={{width:`${Math.max(8,(g.current/g.target)*100)}%`}}/></div><strong>{g.gap?`+${g.gap}`:'Ready'}</strong></div>)}</div><div className="panel gradientPanel"><div className="eyebrow">90-DAY COPILOT</div><h3>Your next best move</h3><p>Complete a Python assessment, add two portfolio projects and apply to roles matching your strongest skills.</p><button className="primary" onClick={()=>go('Career AI')}>Generate roadmap <ChevronRight size={16}/></button></div></div></>}
function CareerAI(){const [q,setQ]=useState('');const [messages,setMessages]=useState([{role:'ai',text:'Hi! I’m your Career Copilot. Ask for a 90-day roadmap, resume feedback, interview prep, skill-gap advice, or role recommendations.'}]);const send=async()=>{if(!q.trim())return;const text=q;setQ('');setMessages(m=>[...m,{role:'user',text}]);const d=await api('/ai/chat',{method:'POST',body:JSON.stringify({message:text})});setMessages(m=>[...m,{role:'ai',text:d.reply}])};return <div className="aiPage"><div className="aiHead"><div className="aiLogo"><Sparkles/></div><div><div className="eyebrow">LOCAL OLLAMA AI</div><h2>Your Career Copilot</h2><p>Private career guidance powered by your local AI model.</p></div></div><div className="chips">{['Create my 90-day career roadmap','Analyze my skill gaps','Prepare me for an interview','How can I improve my resume?'].map(x=><button onClick={()=>setQ(x)}>{x}</button>)}</div><div className="chat">{messages.map(m=><div className={m.role==='ai'?'bubble ai':'bubble user'}>{m.role==='ai'&&<Sparkles size={15}/>}<span>{m.text}</span></div>)}</div><div className="composer"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask your career copilot..."/><button className="primary" onClick={send}><Send size={17}/></button></div></div>}

function ExternalJobs({user,bump}){
 const [items,setItems]=useState([]); const [q,setQ]=useState(''); const [loc,setLoc]=useState('');
 useEffect(()=>{api('/opportunities?kind=JOB').then(setItems).catch(()=>{})},[bump]);
 const linkedin=`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(q||'software developer')}&location=${encodeURIComponent(loc||'India')}`;
 const apply=async id=>{try{await api(`/opportunities/${id}/apply`,{method:'POST',body:JSON.stringify({cover_note:'I found this role through Unique Path and would like to apply.'})});alert('Application saved in Unique Path.')}catch(e){alert(e.message)}};
 return <><div className="pageTitle"><div><div className="eyebrow">LIVE EXTERNAL JOB SEARCH</div><h2>Jobs</h2><p>Search your local Unique Path jobs and jump to LinkedIn for the live external marketplace.</p></div><a className="primary linkButton" href={linkedin} target="_blank" rel="noreferrer"><ExternalLink size={17}/> Search LinkedIn Jobs</a></div>
 <div className="externalSearch panel"><div className="searchField"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Job title, skill or company"/></div><div className="searchField"><Globe size={17}/><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="Location (e.g. Bengaluru)"/></div><a className="primary" href={linkedin} target="_blank" rel="noreferrer">Open LinkedIn search <ExternalLink size={16}/></a></div>
 <div className="integrationCard linkedinCard"><div className="integrationIcon"><BriefcaseBusiness/></div><div><span className="eyebrow">LINKEDIN JOBS</span><h3>Millions of jobs and internships</h3><p>Use LinkedIn's official job search with your keyword and location. Unique Path keeps your profile, skills and application tracker in one place.</p><a href={linkedin} target="_blank" rel="noreferrer">Open LinkedIn Jobs <ExternalLink size={15}/></a></div></div>
 <div className="sectionLabel">Unique Path recruiter opportunities</div><div className="oppGrid">{items.map(o=><div className="oppCard" key={o.id}><div className="oppTop"><span className="tag">JOB</span><span>{o.location}</span></div><h3>{o.title}</h3><b>{o.company}</b><p>{o.description}</p><div className="skillTags">{o.skills.split(',').filter(Boolean).map(s=><span key={s}>{s.trim()}</span>)}</div><div className="oppBottom"><div><b>{o.salary||'Competitive'}</b><small>{o.employment_type}</small></div>{user.role==='STUDENT'&&<button className="primary small" onClick={()=>apply(o.id)}>Apply & track</button>}</div></div>)}</div></>
}
function ExternalInternships({user,bump}){
 const [items,setItems]=useState([]); const [q,setQ]=useState(''); const [loc,setLoc]=useState('');
 useEffect(()=>{api('/opportunities?kind=INTERNSHIP').then(setItems).catch(()=>{})},[bump]);
 const internshala=`https://internshala.com/internships/${q?encodeURIComponent(q.toLowerCase().replace(/\s+/g,'-'))+'-internship/':''}`;
 const apply=async id=>{try{await api(`/opportunities/${id}/apply`,{method:'POST',body:JSON.stringify({cover_note:'I found this internship through Unique Path and would like to apply.'})});alert('Application saved in Unique Path.')}catch(e){alert(e.message)}};
 return <><div className="pageTitle"><div><div className="eyebrow">INTERNSHIP MARKETPLACE</div><h2>Internships</h2><p>Find internships on Unique Path and continue to Internshala for live listings.</p></div><a className="primary linkButton" href={internshala} target="_blank" rel="noreferrer"><ExternalLink size={17}/> Browse Internshala</a></div>
 <div className="externalSearch panel"><div className="searchField"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Internship skill or role"/></div><div className="searchField"><Globe size={17}/><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="Preferred location"/></div><a className="primary" href={internshala} target="_blank" rel="noreferrer">Open Internshala <ExternalLink size={16}/></a></div>
 <div className="integrationCard internshalaCard"><div className="integrationIcon"><GraduationCap/></div><div><span className="eyebrow">INTERNSHALA</span><h3>Internships & student opportunities</h3><p>Internshala is an external marketplace. Unique Path links out to its live search rather than copying or scraping listings.</p><a href={internshala} target="_blank" rel="noreferrer">Open Internshala internships <ExternalLink size={15}/></a></div></div>
 <div className="sectionLabel">Unique Path internships</div><div className="oppGrid">{items.map(o=><div className="oppCard" key={o.id}><div className="oppTop"><span className="tag">INTERNSHIP</span><span>{o.location}</span></div><h3>{o.title}</h3><b>{o.company}</b><p>{o.description}</p><div className="skillTags">{o.skills.split(',').filter(Boolean).map(s=><span key={s}>{s.trim()}</span>)}</div><div className="oppBottom"><div><b>{o.salary||'Stipend varies'}</b><small>{o.employment_type}</small></div>{user.role==='STUDENT'&&<button className="primary small" onClick={()=>apply(o.id)}>Apply & track</button>}</div></div>)}</div></>
}
function ResumeBuilder({user}){
 const templates=[['ATS Classic','ats'],['Modern Edge','modern'],['Executive','executive'],['Fresher Focus','fresher']];
 const [template,setTemplate]=useState(localStorage.getItem('resumeTemplate')||'ats');
 const [f,setF]=useState(()=>JSON.parse(localStorage.getItem('resumeData')||JSON.stringify({name:user.name||'',title:user.headline||'Software Developer',email:user.email||'',phone:user.phone||'',location:user.location||'India',summary:'Motivated professional with strong problem-solving skills and hands-on project experience.',skills:'Python, SQL, React, FastAPI',education:'B.Tech / Degree — Your University — 2026',experience:'Add experience, internship or leadership achievements with measurable results.',projects:'Project Name — what you built, technology used, and measurable outcome.',links:'LinkedIn: https://linkedin.com/in/yourname | GitHub: https://github.com/yourname'})));
 const save=()=>{localStorage.setItem('resumeData',JSON.stringify(f));localStorage.setItem('resumeTemplate',template);alert('Resume saved on this device.')}; const print=()=>window.print();
 return <><div className="pageTitle"><div><div className="eyebrow">RESUME STUDIO</div><h2>Resume Builder</h2><p>ATS-friendly, editable templates with instant print/PDF export.</p></div><div className="buttonRow"><button className="ghost" onClick={save}>Save</button><button className="primary" onClick={print}><Download size={16}/> Print / PDF</button></div></div><div className="templateStrip">{templates.map(t=><button className={template===t[1]?'templatePick active':'templatePick'} onClick={()=>setTemplate(t[1])} key={t[1]}><LayoutTemplate size={17}/><b>{t[0]}</b><span>Preview</span></button>)}</div><div className="builderGrid"><div className="panel editor"><h3>Resume content</h3><Form form={f} setForm={setF} fields={['name','title','email','phone','location','summary','skills','education','experience','projects','links']}/><div className="tipBox"><Check size={16}/><span>Best practice: keep it clean, measurable and easy for ATS software to parse. Put your strongest achievements first.</span></div></div><div className={'resumePreview '+template}><div className="resumeName">{f.name}</div><div className="resumeTitle">{f.title}</div><div className="resumeContact">{f.email} · {f.phone} · {f.location}</div><ResumeSection title="SUMMARY" text={f.summary}/><ResumeSection title="SKILLS" text={f.skills}/><ResumeSection title="EXPERIENCE" text={f.experience}/><ResumeSection title="PROJECTS" text={f.projects}/><ResumeSection title="EDUCATION" text={f.education}/><ResumeSection title="LINKS" text={f.links}/></div></div></>
}
function ResumeSection({title,text}){return <section className="resumeSection"><h4>{title}</h4><p>{text}</p></section>}
function CareerTools({user}){
 const [role,setRole]=useState('Software Developer'); const [company,setCompany]=useState('your target company'); const [letter,setLetter]=useState('');
 const generate=()=>setLetter(`Dear Hiring Team at ${company},\n\nI am excited to apply for the ${role} opportunity. My background in practical projects, problem solving and continuous learning aligns with the role. I would welcome the chance to discuss how I can contribute to your team.\n\nThank you for your consideration.\n\nSincerely,\n${user.name}`);
 const questions=['Tell me about yourself.','Explain a project you are proud of.','What is your strongest technical skill?','Describe a difficult problem and how you solved it.','Why should we hire you?','Where do you want to grow in the next 2 years?'];
 return <><div className="pageTitle"><div><div className="eyebrow">CAREER TOOLKIT</div><h2>Career Tools</h2><p>Practical tools for applications, interviews and professional branding.</p></div></div><div className="toolGrid"><div className="panel"><div className="cardIcon"><Mail/></div><h3>Cover letter generator</h3><div className="formGrid"><label>Target role<input value={role} onChange={e=>setRole(e.target.value)}/></label><label>Company<input value={company} onChange={e=>setCompany(e.target.value)}/></label></div><button className="primary" onClick={generate}><Sparkles size={16}/> Draft cover letter</button>{letter&&<textarea className="letterBox" value={letter} onChange={e=>setLetter(e.target.value)}/>}</div><div className="panel"><div className="cardIcon"><Video/></div><h3>Interview practice</h3><p>Use these questions with Career AI for mock interview feedback.</p>{questions.map((q,i)=><button className="questionLink" key={i} onClick={()=>navigator.clipboard?.writeText(q)}>{i+1}. {q}<ChevronRight size={15}/></button>)}</div><div className="panel"><div className="cardIcon"><Award/></div><h3>Career checklist</h3>{['Complete skills profile','Finish at least one assessment','Build 2–3 portfolio projects','Create an ATS-friendly resume','Add measurable achievements','Practice interview answers','Apply and track opportunities'].map(x=><div className="checkLine"><Check size={15}/>{x}</div>)}</div></div></>
}
function Opportunities({user,bump}){const [items,setItems]=useState([]);const [kind,setKind]=useState('');const [show,setShow]=useState(false);const [form,setForm]=useState({kind:'JOB',title:'',company:user.name,location:'Remote',description:'',skills:'',salary:'',employment_type:'Full-time',deadline:''});useEffect(()=>{api('/opportunities'+(kind?`?kind=${kind}`:'')).then(setItems)},[kind]);const create=async()=>{await api('/opportunities',{method:'POST',body:JSON.stringify(form)});setShow(false);bump();api('/opportunities').then(setItems)};const apply=async id=>{await api(`/opportunities/${id}/apply`,{method:'POST',body:JSON.stringify({cover_note:'I am excited to apply for this opportunity.'})});alert('Application submitted!');bump()};return <><div className="pageTitle"><div><div className="eyebrow">MARKETPLACE</div><h2>Opportunities</h2><p>Discover internships and jobs matched to your skills.</p></div>{['INDUSTRY','ADMIN'].includes(user.role)&&<button className="primary" onClick={()=>setShow(true)}><Plus size={17}/> Post opportunity</button>}</div><div className="filters"><button className={!kind?'active':''} onClick={()=>setKind('')}>All</button><button className={kind==='JOB'?'active':''} onClick={()=>setKind('JOB')}>Jobs</button><button className={kind==='INTERNSHIP'?'active':''} onClick={()=>setKind('INTERNSHIP')}>Internships</button><div className="search"><Search size={16}/><input placeholder="Search roles, skills, companies"/></div></div><div className="oppGrid">{items.map(o=><div className="oppCard"><div className="oppTop"><span className="tag">{o.kind}</span><span>{o.location}</span></div><h3>{o.title}</h3><b>{o.company}</b><p>{o.description}</p><div className="skillTags">{o.skills.split(',').map(s=><span>{s.trim()}</span>)}</div><div className="oppBottom"><div><b>{o.salary||'Competitive'}</b><small>{o.employment_type}</small></div>{user.role==='STUDENT'&&<button className="primary small" onClick={()=>apply(o.id)}>Apply now</button>}</div></div>)}</div>{show&&<Modal title="Post an opportunity" close={()=>setShow(false)}><Form form={form} setForm={setForm} fields={['title','company','location','description','skills','salary','employment_type','deadline']}/><button className="primary" onClick={create}>Publish opportunity</button></Modal>}</>}
function Assessments({bump}){const [a,setA]=useState([]);useEffect(()=>{api('/assessments').then(setA)},[]);const submit=async id=>{const score=Number(prompt('Enter your score (0-100) for this demo assessment:','80'));if(Number.isFinite(score)){await api('/assessments/submit',{method:'POST',body:JSON.stringify({assessment_id:id,score})});bump();alert('Assessment recorded.')}};return <><div className="pageTitle"><div><div className="eyebrow">MEASURE & IMPROVE</div><h2>Assessments</h2><p>Validate skills and feed the recommendation engine.</p></div></div><div className="cardGrid">{a.map(x=><div className="featureCard"><div className="cardIcon"><Target/></div><span className="tag">{x.difficulty}</span><h3>{x.title}</h3><p>{x.questions.length} questions · {x.duration} minutes</p><div className="questionPreview">{x.questions.map(q=><div>✓ {q}</div>)}</div><button className="primary" onClick={()=>submit(x.id)}>Start assessment <ChevronRight size={16}/></button></div>)}</div></>}
function Skills(){const [all,setAll]=useState([]);const [mine,setMine]=useState([]);const [gaps,setGaps]=useState([]);const [sel,setSel]=useState('');useEffect(()=>{api('/skills').then(setAll);api('/my-skills').then(setMine);api('/skill-gap').then(setGaps)},[]);const add=async()=>{if(!sel)return;await api('/my-skills',{method:'POST',body:JSON.stringify({skill_id:Number(sel),level:4,evidence:'Added from skills dashboard'})});setMine(await api('/my-skills'));setGaps(await api('/skill-gap'))};return <><div className="pageTitle"><div><div className="eyebrow">SKILL GRAPH</div><h2>Skills & Gap Analysis</h2><p>Build your skill graph and see where the market is pulling.</p></div></div><div className="grid2"><div className="panel"><div className="panelHead"><h3>My skills</h3></div><div className="addSkill"><select value={sel} onChange={e=>setSel(e.target.value)}><option value="">Choose a skill</option>{all.filter(s=>!mine.some(m=>m.id===s.id)).map(s=><option value={s.id}>{s.name}</option>)}</select><button className="primary" onClick={add}><Plus size={16}/> Add</button></div>{mine.map(s=><div className="skillRow"><div><b>{s.name}</b><small>{s.category}</small></div><div className="level">{'●'.repeat(s.level)}{'○'.repeat(4-s.level)}</div></div>)}</div><div className="panel"><div className="panelHead"><h3>Priority gaps</h3></div>{gaps.map(g=><div className="gapRow"><div><b>{g.skill}</b><span>Current {g.current}/4</span></div><div className="bar"><i style={{width:`${(g.current/g.target)*100}%`}}/></div><strong>{g.gap?'Gap '+g.gap:'Ready'}</strong></div>)}</div></div></>}
function Portfolio({bump}){
 const [p,setP]=useState([]); const [show,setShow]=useState(false); const [template,setTemplate]=useState(localStorage.getItem('portfolioTemplate')||'showcase');
 const [form,setForm]=useState({title:'',description:'',tech_stack:'',project_url:'',image_url:''});
 useEffect(()=>{api('/portfolio').then(setP)},[]);
 const add=async()=>{await api('/portfolio',{method:'POST',body:JSON.stringify(form)});setP(await api('/portfolio'));setShow(false);bump()};
 const saveTemplate=()=>{localStorage.setItem('portfolioTemplate',template);alert('Portfolio template saved on this device.')};
 return <><div className="pageTitle"><div><div className="eyebrow">PROOF OF WORK</div><h2>Portfolio Studio</h2><p>Choose a template, add project evidence and publish a recruiter-ready portfolio.</p></div><div className="buttonRow"><button className="ghost" onClick={saveTemplate}>Save template</button><button className="primary" onClick={()=>setShow(true)}><Plus size={17}/> Add project</button></div></div>
 <div className="templateStrip">{[['Showcase','showcase'],['Minimal','minimal'],['Developer','developer'],['Creative','creative']].map(t=><button className={template===t[1]?'templatePick active':'templatePick'} onClick={()=>setTemplate(t[1])} key={t[1]}><Palette size={17}/><b>{t[0]}</b><span>Preview</span></button>)}</div>
 <div className={'portfolioHero '+template}><div><span className="eyebrow">{template.toUpperCase()} PORTFOLIO</span><h2>{localStorage.getItem('resumeData')?JSON.parse(localStorage.getItem('resumeData')).name:'Your Name'}</h2><p>{localStorage.getItem('resumeData')?JSON.parse(localStorage.getItem('resumeData')).title:'Your professional headline'}</p></div><div className="portfolioStats"><b>{p.length}</b><span>Projects</span></div></div>
 <div className="projectGrid">{p.map(x=><div className={'projectCard '+template} key={x.id}><div className="projectVisual">{x.image_url?<img src={x.image_url} alt=""/>:<Sparkles/>}</div><div className="projectBody"><h3>{x.title}</h3><p>{x.description}</p><div className="skillTags">{x.tech_stack.split(',').filter(Boolean).map(s=><span key={s}>{s.trim()}</span>)}</div>{x.project_url&&<a href={x.project_url} target="_blank" rel="noreferrer">View project ↗</a>}</div></div>)}{!p.length&&<div className="empty">Your portfolio is empty. Add your first project.</div>}</div>
 {show&&<Modal title="Add portfolio project" close={()=>setShow(false)}><Form form={form} setForm={setForm} fields={['title','description','tech_stack','project_url','image_url']}/><button className="primary" onClick={add}>Save project</button></Modal>}</>}
function Learning(){
 const [c,setC]=useState([]); useEffect(()=>{api('/courses').then(setC).catch(()=>{})},[]);
 const platforms=[
  ['Coursera','University and industry courses across AI, data, software and business.','https://www.coursera.org/courses?query=free','Free courses'],
  ['edX','University-backed courses with videos, readings, discussions and assessments.','https://www.edx.org/learn','University learning'],
  ['freeCodeCamp','Hands-on coding paths for web development, Python, data and more.','https://www.freecodecamp.org/learn/','Practice-first'],
  ['MIT OpenCourseWare','Free university course materials from MIT.','https://ocw.mit.edu/search/','Academic depth'],
  ['Khan Academy','Interactive foundations for computing, math, statistics and more.','https://www.khanacademy.org/','Beginner friendly'],
  ['Google Skillshop','Google product and digital-skills training with certifications on selected tracks.','https://skillshop.withgoogle.com/','Career skills']
 ];
 const quizzes=[
  {title:'AI & Data Basics',level:'Beginner',qs:[['Which Python structure stores key-value pairs?',['List','Dictionary','Tuple','Set'],1],['What does SQL SELECT do?',['Deletes rows','Retrieves data','Creates a server','Compiles code'],1],['What is a model trained to do in supervised learning?',['Map inputs to known targets','Only store files','Design UI','Send emails'],0]]},
  {title:'Frontend Fundamentals',level:'Beginner',qs:[['Which library is used to build component-based UIs?',['React','MySQL','FastAPI','Ollama'],0],['Which language styles web pages?',['SQL','CSS','Python','Bash'],1],['What does an API commonly provide?',['A contract for software communication','A resume template','A database backup','A laptop'],0]]},
  {title:'Career Readiness',level:'All levels',qs:[['What should you tailor to a job description?',['Resume keywords and evidence','Your password','Your browser theme','Your email provider'],0],['What is a strong portfolio project?',['A copied tutorial only','A project with context, contribution and outcome','An empty repository','Only a logo'],1],['What should an ATS-friendly resume prioritize?',['Readable structure and relevant keywords','Complex graphics','Multiple columns','Text inside images'],0]]}
 ];
 const [tab,setTab]=useState('platforms'); const [quiz,setQuiz]=useState(null); const [answers,setAnswers]=useState({}); const [result,setResult]=useState(null);
 const start=q=>{setQuiz(q);setAnswers({});setResult(null)};
 const finish=()=>{let score=0;quiz.qs.forEach((q,i)=>{if(Number(answers[i])===q[2])score++});setResult(Math.round(score/quiz.qs.length*100))};
 return <><div className="pageTitle"><div><div className="eyebrow">LEARN · PRACTICE · PROVE</div><h2>Learning & Quiz Center</h2><p>Open trusted learning platforms, build practical knowledge, then test yourself with quick career quizzes.</p></div><div className="buttonRow"><button className={tab==='platforms'?'primary':'ghost'} onClick={()=>setTab('platforms')}><BookOpen size={16}/> Learning platforms</button><button className={tab==='quizzes'?'primary':'ghost'} onClick={()=>setTab('quizzes')}><Target size={16}/> Quizzes</button></div></div>
 {tab==='platforms'&&<><div className="learningBanner"><div><div className="eyebrow">ONE PLACE · MANY PATHS</div><h3>Learn from leading platforms</h3><p>Each button opens the provider's official learning site in a new tab, so users can continue learning without leaving Unique Path.</p></div><GraduationCap size={48}/></div><div className="cardGrid">{platforms.map(x=><div className="featureCard learningCard"><div className="cardIcon"><GraduationCap/></div><span className="tag">{x[3]}</span><h3>{x[0]}</h3><p>{x[1]}</p><button className="primary" onClick={()=>window.open(x[2],'_blank','noopener,noreferrer')}>Open platform <ExternalLink size={16}/></button></div>)}</div><h3 className="sectionTitle">Recommended tracks inside Unique Path</h3><div className="cardGrid">{c.map(x=><div className="featureCard"><div className="cardIcon"><BookOpen/></div><span className="tag">{x.category}</span><h3>{x.title}</h3><p>{x.provider} · {x.level} · {x.duration}</p>{x.url?<button className="ghost" onClick={()=>window.open(x.url,'_blank','noopener,noreferrer')}>Start learning <ChevronRight size={16}/></button>:<span className="muted">Platform link coming soon</span>}</div>)}</div></>}
 {tab==='quizzes'&&<>{!quiz?<div className="cardGrid">{quizzes.map(q=><div className="featureCard"><div className="cardIcon"><Target/></div><span className="tag">{q.level}</span><h3>{q.title}</h3><p>{q.qs.length} questions · instant score</p><button className="primary" onClick={()=>start(q)}>Start quiz <PlayCircle size={16}/></button></div>)}</div>:<div className="panel quizPanel"><div className="panelHead"><div><div className="eyebrow">QUIZ MODE</div><h3>{quiz.title}</h3></div><button className="ghost" onClick={()=>setQuiz(null)}>Back to quizzes</button></div>{quiz.qs.map((q,i)=><div className="quizQuestion"><b>{i+1}. {q[0]}</b>{q[1].map((a,j)=><label><input type="radio" name={'q'+i} checked={String(answers[i])===String(j)} onChange={()=>setAnswers({...answers,[i]:j})}/>{a}</label>)}</div>)}{result===null?<button className="primary" onClick={finish}>Submit quiz <CheckCircle2 size={16}/></button>:<div className="quizResult"><div className="scoreCircle">{result}%</div><div><h3>{result>=80?'Excellent work!':result>=60?'Good progress!':'Keep practicing!'}</h3><p>Your score is saved on this screen. Review the learning platforms and try again to improve.</p><button className="ghost" onClick={()=>{setAnswers({});setResult(null)}}>Retake quiz</button></div></div>}</div>}</>}</>}
function ATSScore(){
 const [resume,setResume]=useState(()=>{try{const r=JSON.parse(localStorage.getItem('resumeData')||'{}');return [r.name,r.title,r.summary,r.experience,r.education,r.skills].filter(Boolean).join('\n')}catch{return ''}});
 const [jd,setJd]=useState(''); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false);
 const score=async()=>{if(!resume.trim()||!jd.trim())return alert('Add both your resume text and the job description.');setLoading(true);try{setResult(await api('/ats/score',{method:'POST',body:JSON.stringify({resume_text:resume,job_description:jd})}))}finally{setLoading(false)}};
 return <><div className="pageTitle"><div><div className="eyebrow">RESUME INTELLIGENCE</div><h2>ATS Score Checker</h2><p>Compare your resume with a specific job description and identify missing keywords before you apply.</p></div><a className="ghost linkBtn" href="https://www.jobscan.co/resume-scanner" target="_blank" rel="noreferrer"><ExternalLink size={16}/> Open Jobscan</a></div><div className="atsGrid"><div className="panel"><label className="wideLabel">Your resume text<textarea className="atsArea" value={resume} onChange={e=>setResume(e.target.value)} placeholder="Paste your resume text here..."/></label><label className="wideLabel">Job description<textarea className="atsArea" value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste the target job description here..."/></label><button className="primary" onClick={score} disabled={loading}>{loading?'Checking...':'Check ATS score'} <SearchCode size={17}/></button></div>{result?<div className="panel atsResult"><div className="scoreCircle big">{result.score}%</div><h3>{result.score>=75?'Strong match':'Needs improvement'}</h3><p>{result.tip}</p><h4>Matched keywords</h4><div className="skillTags">{result.matched_keywords.map(x=><span>{x}</span>)}</div><h4>Missing keywords</h4><div className="skillTags missing">{result.missing_keywords.map(x=><span>{x}</span>)}</div><small>Tip: external ATS tools can calculate scores differently. Use this score as a practical comparison, not a guarantee of employer ATS behavior.</small></div>:<div className="panel empty"><SearchCode size={40}/><h3>Your score will appear here</h3><p>Use the same job description you are targeting for a more useful comparison.</p></div>}</div></>}
function Mentors(){const [m,setM]=useState([]);useEffect(()=>{api('/mentors').then(setM)},[]);const req=async id=>{await api('/mentors/request',{method:'POST',body:JSON.stringify({mentor_id:id,message:'I would like career guidance.'})});alert('Mentor request sent!')};return <><div className="pageTitle"><div><div className="eyebrow">HUMAN GUIDANCE</div><h2>Mentors</h2><p>Find experienced people for focused career conversations.</p></div></div><div className="mentorGrid">{m.map(x=><div className="mentor"><div className="mentorAvatar">{x.name[0]}</div><h3>{x.name}</h3><b>{x.company}</b><p>{x.expertise}</p><div className="rating">★ {x.rating} · {x.experience_years} yrs</div><button className="primary" onClick={()=>req(x.id)}>Request session</button></div>)}</div></>}
function Profile({user,setUser}){const [f,setF]=useState({name:user.name,headline:user.headline||'',location:user.location||'',bio:user.bio||'',phone:user.phone||''});const save=async()=>{const u=await api('/profile',{method:'PUT',body:JSON.stringify(f)});localStorage.setItem('user',JSON.stringify(u));setUser(u);alert('Profile saved')};return <><div className="pageTitle"><div><div className="eyebrow">IDENTITY</div><h2>My profile</h2><p>Keep your career identity current and recruiter-ready.</p></div><button className="primary" onClick={save}>Save changes</button></div><div className="profilePanel"><div className="bigAvatar">{f.name?.[0]}</div><div className="profileForm"><Form form={f} setForm={setF} fields={['name','headline','location','phone','bio']}/></div></div></>}
function Applications(){const [a,setA]=useState([]);useEffect(()=>{api('/applications').then(setA).catch(()=>{})},[]);return <><div className="pageTitle"><div><div className="eyebrow">PIPELINE</div><h2>My applications</h2><p>Track every opportunity from applied to offer.</p></div></div><div className="panel tablePanel"><table><thead><tr><th>Role</th><th>Company</th><th>Type</th><th>Status</th><th>Date</th></tr></thead><tbody>{a.map(x=><tr><td><b>{x.title}</b></td><td>{x.company}</td><td>{x.kind}</td><td><span className="status">{x.status}</span></td><td>{new Date(x.applied_at).toLocaleDateString()}</td></tr>)}</tbody></table>{!a.length&&<div className="empty">No applications yet. Explore opportunities and apply.</div>}</div></>}
function Admin(){const [a,setA]=useState({});useEffect(()=>{api('/analytics').then(setA)},[]);return <><div className="pageTitle"><div><div className="eyebrow">CONTROL CENTER</div><h2>Admin analytics</h2><p>Monitor platform health and career ecosystem activity.</p></div></div><div className="statGrid">{Object.entries(a).map(([k,v])=><div className="stat"><span>✦</span><b>{v}</b><small>{k}</small></div>)}</div><div className="panel"><h3>Platform modules</h3><div className="moduleList">{['Authentication & RBAC','Student profiles & skills','Assessments & skill-gap engine','Jobs & internships','Applications & recruiter workflow','Portfolio builder','Mentors & requests','Learning paths','Notifications','Local Ollama AI copilot','Analytics'].map(x=><div><CheckCircle2 size={17}/> {x}<span>Active</span></div>)}</div></div></>}
function Form({form,setForm,fields}){return <div className="formGrid">{fields.map(k=><label>{k.replaceAll('_',' ')}<>{k==='description'||k==='bio'?<textarea value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>:<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</></label>)}</div>}
function Modal({title,close,children}){return <div className="modalBack"><div className="modal"><div className="modalHead"><h3>{title}</h3><button className="icon" onClick={close}><X/></button></div>{children}</div></div>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
