import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {BrowserRouter} from "react-router-dom";
import * as I from "lucide-react";
import "./styles.css";

const API=(import.meta.env.VITE_API_URL||"http://127.0.0.1:8000/api").replace(/\/$/,"");
async function api(path,opt={}){
 const token=localStorage.getItem("token");
 const headers={...(opt.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(opt.headers||{})};
 if(token) headers.Authorization=`Bearer ${token}`;
 const r=await fetch(API+path,{...opt,headers});
 let d={}; try{d=await r.json()}catch{}
 if(!r.ok) throw new Error(d.detail||"Something went wrong");
 return d;
}
function useAsync(fn,deps=[]){const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{let ok=true;setLoading(true);fn().then(x=>ok&&setData(x)).catch(e=>ok&&setError(e.message)).finally(()=>ok&&setLoading(false));return()=>{ok=false}},deps);return{data,loading,error,setData}}
function Button({children,loading,...p}){return <button {...p} className={(p.className||"")+" ripple"} disabled={p.disabled||loading}>{loading?<><I.Loader2 size={16} className="spin"/> Working…</>:children}</button>}
function Toast({toast}){return toast?<div className={"toast "+toast.type}>{toast.type==="ok"?<I.CheckCircle2/>:<I.AlertCircle/>}{toast.text}</div>:null}
function App(){
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem("user")||"null"));
 const [page,setPage]=useState("Dashboard"),[toast,setToast]=useState(null);
 const notify=(text,type="ok")=>{setToast({text,type});setTimeout(()=>setToast(null),2800)};
 if(!user)return <Auth onLogin={u=>{setUser(u);setPage("Dashboard")}} notify={notify}/>;
 const go=p=>setPage(p);
 return <div><Shell user={user} page={page} go={go} logout={()=>{localStorage.clear();setUser(null)}}/><main className="main">{page==="Dashboard"&&<Dashboard user={user} go={go}/>}
 {page==="Career AI"&&<CareerAI notify={notify}/>}
 {page==="Career DNA"&&<CareerDNA go={go}/>}
 {page==="Future Self"&&<FutureSelf/>}
 {page==="Career Lab"&&<CareerLab notify={notify}/>}
 {page==="Project Builder"&&<ProjectBuilder notify={notify}/>}
 {page==="Job Match AI"&&<JobMatch/>}
 {page==="Opportunity Radar"&&<OpportunityRadar/>}
 {page==="Career Mirror"&&<CareerMirror/>}
 {page==="Skill Graph"&&<SkillGraph/>}
 {page==="Career Twin"&&<CareerTwin/>}
 {page==="Growth Simulator"&&<GrowthSimulator/>}
 {page==="Skill Assessment"&&<Assessment notify={notify}/>}
 {page==="Skill Gap"&&<Skills notify={notify}/>}
 {page==="Jobs"&&<Jobs user={user} notify={notify}/>}
 {page==="Internships"&&<Internships user={user} notify={notify}/>}
 {page==="Resume Studio"&&<Resume user={user} notify={notify}/>}
 {page==="Portfolio Studio"&&<Portfolio notify={notify}/>}
 {page==="Learning & Quiz"&&<Learning notify={notify}/>}
 {page==="ATS Score"&&<ATS notify={notify}/>}
 {page==="Mentors"&&<Mentors user={user} notify={notify}/>}
 {page==="Career Tools"&&<Tools user={user} notify={notify}/>}
 {page==="Applications"&&<Applications/>}
 {page==="My Profile"&&<Profile user={user} setUser={setUser} notify={notify}/>}
 {page==="Industry Hub"&&<Industry user={user} notify={notify}/>}
 {page==="Institution Hub"&&<Institution user={user} notify={notify}/>}
 {page==="Admin"&&<Admin/>}</main><Toast toast={toast}/></div>
}
function Auth({onLogin,notify}){
 const [mode,setMode]=useState("login"),[role,setRole]=useState("STUDENT"),[f,setF]=useState({name:"",email:"",password:""}),[loading,setLoading]=useState(false);
 const submit=async e=>{e.preventDefault();setLoading(true);try{const d=await api(mode==="login"?"/auth/login":"/auth/register",{method:"POST",body:JSON.stringify(mode==="login"?{email:f.email,password:f.password}:{...f,role})});localStorage.setItem("token",d.token);localStorage.setItem("user",JSON.stringify(d.user));onLogin(d.user)}catch(e){notify(e.message,"err")}finally{setLoading(false)}};
 return <div className="loginPage"><div className="orb o1"/><div className="orb o2"/><form className="loginCard" onSubmit={submit}><div className="brand">UNIQUE <span>PATH</span></div><div className="eyebrow">ACADEMIA · INDUSTRY · AI</div><h1>{mode==="login"?"Welcome back":"Create your account"}</h1><p className="muted">{mode==="login"?"Your career workspace is waiting.":"Build your student or industry profile and unlock the career platform."}</p>{mode==="register"&&<label>Name<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label>}<label>Email<input required type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Password<input required minLength={8} type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></label>{mode==="register"&&<div className="rolePick"><button type="button" className={role==="STUDENT"?"selected":""} onClick={()=>setRole("STUDENT")}>Student</button><button type="button" className={role==="INDUSTRY"?"selected":""} onClick={()=>setRole("INDUSTRY")}>Industry</button><button type="button" className={role==="INSTITUTION"?"selected":""} onClick={()=>setRole("INSTITUTION")}>Institution</button></div>}<Button className="primary full" loading={loading}>{mode==="login"?"Sign in":"Create account"}</Button>{mode==="login"&&<div className="demo"><b>Demo accounts</b><br/>student@example.com · password123<br/>industry@example.com · password123<br/>institution@example.com · password123<br/>admin@example.com · password123</div>}<button type="button" className="textBtn center" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"New here? Create an account":"Already have an account? Sign in"}</button></form></div>
}
const nav=[["Dashboard",I.LayoutDashboard],["Career AI",I.Sparkles],["Skill Assessment",I.Target],["Skill Gap",I.Network],["Career DNA",I.Activity],["Future Self",I.Compass],["Career Lab",I.FlaskConical],["Project Builder",I.Hammer],["Job Match AI",I.GitCompare],["Opportunity Radar",I.Radar],["Career Mirror",I.ScanFace],["Skill Graph",I.Share2],["Career Twin",I.Bot],["Growth Simulator",I.TrendingUp],["Learning & Quiz",I.BookOpen],["Jobs",I.BriefcaseBusiness],["Internships",I.GraduationCap],["Resume Studio",I.FileText],["Portfolio Studio",I.Palette],["ATS Score",I.SearchCode],["Mentors",I.Users],["Career Tools",I.Wand2],["Applications",I.ListChecks],["My Profile",I.UserRound]];
function Shell({user,page,go,logout}){return <><aside className="side"><div className="brand">UNIQUE <span>PATH</span></div><div className="sideSub">Created by Umera Sulthana</div><div className="nav">{nav.map(([n,Icon])=><button className={page===n?"active":""} onClick={()=>go(n)} key={n}><Icon size={17}/>{n}</button>)}{user.role!=="STUDENT"&&<button className={page==="Industry Hub"?"active":""} onClick={()=>go("Industry Hub")}><I.Building2 size={17}/>Industry Hub</button>}
 {user.role==="INSTITUTION"&&<button className={page==="Institution Hub"?"active":""} onClick={()=>go("Institution Hub")}><I.School size={17}/>Institution Hub</button>}{user.role==="ADMIN"&&<button onClick={()=>go("Admin")}><I.BarChart3 size={17}/>Admin</button>}</div><div className="sideFoot"><div className="miniAvatar">{user.name[0]}</div><div><b>{user.name}</b><small>{user.role}</small></div><button className="icon" onClick={logout}><I.LogOut size={17}/></button></div></aside><header className="mobileHead"><div className="brand">UNIQUE <span>PATH</span></div><div className="mobileScroll">{nav.slice(0,7).map(([n])=><button className={page===n?"active":""} onClick={()=>go(n)} key={n}>{n}</button>)}</div></header></>}
function Loading(){return <div className="panel loading"><I.Loader2 className="spin"/> Loading live career intelligence…</div>}
function ErrorBox({text}){return <div className="panel errorBox"><I.AlertCircle/> {text}</div>}
function Title({eyebrow,title,sub,children}){return <div className="pageTitle"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2><p>{sub}</p></div><div className="buttonRow">{children}</div></div>}
function Dashboard({user,go}){
 const {data:sRaw}=useAsync(()=>api("/analytics"),[]);
const s={
    ...(sRaw||{}),
    opportunities:sRaw?.opportunities||[],
    applications:sRaw?.applications||[],
    skills:sRaw?.skills||[],
};
const {data:gRaw}=useAsync(()=>api("/skill-gap"),[]);
const g=gRaw||[];
 return <><div className="hero"><div><div className="eyebrow">{user.role} · CAREER INTELLIGENCE</div><h2>Good day, <span>{user.name}</span> 👋</h2><p>One workspace for skills, AI guidance, applications, projects and industry connections.</p><div className="actions"><Button className="primary" onClick={()=>go("Career AI")}><I.Sparkles/> Ask Career AI</Button><Button className="ghost" onClick={()=>go("Skill Assessment")}><I.Target/> Take AI assessment</Button></div></div><div className="heroGraphic"><I.Sparkles size={54}/></div></div><div className="statGrid">{[["Open roles",s.opportunities||0],["Applications",s.applications||0],["Skills tracked",s.skills||0],["Portfolio projects",s.portfolio_projects||0]].map(x=><div className="stat" key={x[0]}><b>{x[1]}</b><small>{x[0]}</small></div>)}</div><div className="grid2"><div className="panel"><div className="panelHead"><div><h3>Priority skill gaps</h3><p>What to learn next for open opportunities.</p></div><Button className="textBtn" onClick={()=>go("Skill Gap")}>View plan</Button></div>{g.slice(0,5).map(x=><div className="gapRow" key={x.skill}><div><b>{x.skill}</b><span>Level {x.current}/4 → {x.target}/4</span></div><div className="bar"><i style={{width:`${Math.max(7,x.current/x.target*100)}%`}}/></div><strong>{x.gap?`Gap ${x.gap}`:"Ready"}</strong></div>)}</div><div className="panel gradientPanel"><div className="eyebrow">PERSONALIZED NEXT STEP</div><h3>Build evidence, not just skills.</h3><p>Take a role-specific assessment, turn weak areas into a mini-project, then update your resume and portfolio.</p><Button className="primary" onClick={()=>go("Resume Studio")}>Open Resume Studio <I.ChevronRight/></Button></div></div></>
}
function CareerAI({notify}){
 const [q,setQ]=useState(""),[msgs,setMsgs]=useState([{role:"ai",text:"Hi! I’m your Career Copilot. I can create a roadmap, explain skill gaps, improve a resume, prepare interview answers, or suggest projects."}]),[loading,setLoading]=useState(false);
 const send=async()=>{if(!q.trim())return;const text=q;setQ("");setMsgs(m=>[...m,{role:"user",text}]);setLoading(true);try{const d=await api("/ai/chat",{method:"POST",body:JSON.stringify({message:text})});setMsgs(m=>[...m,{role:"ai",text:d.reply}])}catch(e){notify(e.message,"err")}finally{setLoading(false)}};
 return <div className="aiPage"><Title eyebrow="LOCAL OLLAMA AI" title="Career Copilot" sub="Personalized career guidance using your local AI model."/><div className="chips">{["Create a 90-day roadmap","Analyze my skill gaps","Prepare me for a React interview","Improve my resume summary"].map(x=><button key={x} onClick={()=>setQ(x)}>{x}</button>)}</div><div className="chat">{msgs.map((m,i)=><div className={"bubble "+m.role} key={i}>{m.role==="ai"&&<I.Sparkles size={15}/>}<span>{m.text}</span></div>)}</div><div className="composer"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask anything about your career…"/><Button className="primary" onClick={send} loading={loading}><I.Send/></Button></div></div>
}
function Assessment({notify}){
 const [role,setRole]=useState("Software Developer"),[skills,setSkills]=useState("Python, React, SQL"),[difficulty,setDifficulty]=useState("Intermediate"),[test,setTest]=useState(null),[ans,setAns]=useState({}),[result,setResult]=useState(null),[loading,setLoading]=useState(false);
 const generate=async()=>{setLoading(true);try{const d=await api("/assessments/generate",{method:"POST",body:JSON.stringify({role,skills:skills.split(",").map(x=>x.trim()).filter(Boolean),difficulty,count:8})});setTest(d);setAns({});setResult(null)}catch(e){notify(e.message,"err")}finally{setLoading(false)}};
 const finish=async()=>{let correct=0;(test.questions||[]).forEach((q,i)=>{if(Number(ans[i])===Number(q.answer))correct++});const score=Math.round(correct/(test.questions.length||1)*100);try{const d=await api("/assessments/grade",{method:"POST",body:JSON.stringify({title:`${role} AI Assessment`,score,correct,total:test.questions.length,role})});setResult(d);notify("Assessment completed")}catch(e){notify(e.message,"err")}};
 if(test&&!result)return <><Title eyebrow="AI SKILL ASSESSMENT" title={test.role} sub={`${test.difficulty} · ${test.questions.length} questions`}><Button className="ghost" onClick={()=>setTest(null)}>Exit</Button></Title><div className="panel quizPanel">{test.questions.map((q,i)=><div className="quizQuestion" key={i}><b>{i+1}. {q.question}</b>{q.options.map((o,j)=><label key={j}><input type="radio" name={"q"+i} checked={String(ans[i])===String(j)} onChange={()=>setAns({...ans,[i]:j})}/>{o}</label>)}</div>)}<Button className="primary" onClick={finish}>Submit assessment <I.CheckCircle2/></Button></div></>;
 if(result)return <div className="resultHero"><div className="scoreCircle big">{result.score}%</div><div><div className="eyebrow">ASSESSMENT COMPLETE</div><h2>{result.score>=80?"Excellent result!":result.score>=60?"Good progress!":"Keep practicing!"}</h2><p>{result.correct}/{result.total} answers correct. Use the explanations and skill-gap plan to improve.</p><Button className="primary" onClick={()=>setTest(null)}>Create another assessment</Button></div></div>;
 return <><Title eyebrow="MEASURE · PRACTICE · PROVE" title="AI Skill Assessment" sub="Generate questions for the exact role you want, answer them, and receive a score."><Button className="primary" onClick={generate} loading={loading}><I.Sparkles/> Generate assessment</Button></Title><div className="panel formGrid three"><label>Target job role<input value={role} onChange={e=>setRole(e.target.value)}/></label><label>Skills to test<input value={skills} onChange={e=>setSkills(e.target.value)}/></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label></div><div className="infoGrid"><Info icon={I.Target} title="Role-specific questions" text="Questions are generated around your target role and selected skills."/><Info icon={I.BarChart3} title="Instant scoring" text="Your answers are checked immediately and the result is stored in your account."/><Info icon={I.Route} title="Next-step guidance" text="Use Skill Gap Analysis to turn weak areas into a learning plan."/><Info icon={I.Sparkles} title="AI powered" text="Ollama generates practical, scenario-based questions." /></div></>
}
function Info({icon:Icon,title,text}){return <div className="featureCard"><div className="cardIcon"><Icon/></div><h3>{title}</h3><p>{text}</p></div>}
function Skills({notify}){
 const {data:all=[]}=useAsync(()=>api("/skills"),[]),{data:mine0=[]}=useAsync(()=>api("/my-skills"),[]),{data:gaps=[]}=useAsync(()=>api("/skill-gap"),[]);
 const [mine,setMine]=useState([]),[sel,setSel]=useState(""),[level,setLevel]=useState(3),[busy,setBusy]=useState(false);
 useEffect(()=>setMine(mine0),[mine0]);
 const add=async()=>{if(!sel)return;setBusy(true);try{await api("/my-skills",{method:"POST",body:JSON.stringify({skill_id:+sel,level,evidence:"Self-assessed on Unique Path"})});setMine(await api("/my-skills"));notify("Skill added")}catch(e){notify(e.message,"err")}finally{setBusy(false)}};
 return <><Title eyebrow="SKILL GRAPH" title="Skill Gap Analysis" sub="See what the market asks for, what you already have, and exactly how to close the gap."/><div className="grid2"><div className="panel"><h3>Your skills</h3><div className="addSkill"><select value={sel} onChange={e=>setSel(e.target.value)}><option value="">Choose skill</option>{all.filter(s=>!mine.some(m=>m.id===s.id)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={level} onChange={e=>setLevel(+e.target.value)}><option value="1">1/4</option><option value="2">2/4</option><option value="3">3/4</option><option value="4">4/4</option></select><Button className="primary" onClick={add} loading={busy}>Add</Button></div>{mine.map(s=><div className="skillRow" key={s.id}><div><b>{s.name}</b><small>{s.category}</small></div><span className="level">{'●'.repeat(s.level)}{'○'.repeat(4-s.level)}</span></div>)}</div><div className="panel"><h3>What to learn next</h3>{gaps.map(g=><div className="gapPlan" key={g.skill}><div className="gapHead"><b>{g.skill}</b><span>{g.gap?`Gap ${g.gap}`:"Ready"}</span></div><p><b>Learn:</b> {g.what_to_learn}</p><div className="learnSteps">{g.how_to_learn.map((x,i)=><span key={i}>{i+1}. {x}</span>)}</div></div>)}</div></div></>
}
function Jobs({user,notify}){return <OpportunityMarket kind="JOB" user={user} notify={notify} external="https://www.linkedin.com/jobs/"/>}
function Internships({user,notify}){return <OpportunityMarket kind="INTERNSHIP" user={user} notify={notify} external="https://internshala.com/internships/"/>}
function OpportunityMarket({kind,user,notify,external}){
 const [q,setQ]=useState(""),[loc,setLoc]=useState(""),[items,setItems]=useState([]),[loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);try{setItems(await api(`/opportunities?kind=${kind}&q=${encodeURIComponent(q)}&location=${encodeURIComponent(loc)}`))}catch(e){notify(e.message,"err")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const ext=kind==="JOB"?`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(q||"software developer")}&location=${encodeURIComponent(loc||"India")}`:`https://internshala.com/internships/${q?encodeURIComponent(q.toLowerCase().replace(/\s+/g,"-"))+"-internship/":""}`;
 const apply=async id=>{try{await api(`/opportunities/${id}/apply`,{method:"POST",body:JSON.stringify({cover_note:`I found this ${kind.toLowerCase()} through Unique Path.`})});notify("Application saved and tracked")}catch(e){notify(e.message,"err")}};
 return <><Title eyebrow={kind==="JOB"?"JOB MARKETPLACE":"INTERNSHIP MARKETPLACE"} title={kind==="JOB"?"Jobs":"Internships"} sub="Search Unique Path opportunities, then continue to the live external marketplace." ><a className="primary linkButton" href={ext} target="_blank" rel="noreferrer"><I.ExternalLink/> {kind==="JOB"?"LinkedIn Jobs":"Internshala"}</a></Title><div className="externalSearch panel"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={kind==="JOB"?"Role, skill or company":"Internship role or skill"}/><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="Location"/><Button className="primary" onClick={load} loading={loading}><I.Search/> Search</Button></div><div className="integrationCard"><div className="integrationIcon"><I.BriefcaseBusiness/></div><div><div className="eyebrow">LIVE MARKETPLACE LINK</div><h3>{kind==="JOB"?"LinkedIn Jobs":"Internshala"}</h3><p>Unique Path does not scrape external sites. Your search is converted into an official external search link.</p><a href={ext} target="_blank" rel="noreferrer">Open live search <I.ExternalLink size={15}/></a></div></div><div className="sectionLabel">Unique Path {kind.toLowerCase()}s</div><div className="oppGrid">{items.map(o=><div className="oppCard" key={o.id}><div className="oppTop"><span className="tag">{o.kind}</span><span>{o.location}</span></div><h3>{o.title}</h3><b>{o.company}</b><p>{o.description}</p><div className="skillTags">{o.skills.split(",").filter(Boolean).map(s=><span key={s}>{s.trim()}</span>)}</div><div className="oppBottom"><div><b>{o.salary||"Competitive"}</b><small>{o.employment_type}</small></div>{user.role==="STUDENT"&&<Button className="primary small" onClick={()=>apply(o.id)}>Apply & track</Button>}</div></div>)}</div></>
}
function Resume({user,notify}){
 const templates=[["ATS Classic","ats"],["Modern Edge","modern"],["Executive","executive"],["Fresher Focus","fresher"]];
 const defaults={name:user.name,title:user.headline||"Software Developer",email:user.email,phone:user.phone||"",location:user.location||"India",summary:"Write a 3–4 line value proposition focused on the target role.",skills:"Python, SQL, React, FastAPI",education:"Degree — University — Year",experience:"Role / Organization — achievement with a measurable result.",projects:"Project — problem, solution, technologies, outcome.",links:"LinkedIn | GitHub | Portfolio"};
 const [template,setTemplate]=useState(localStorage.getItem("resumeTemplate")||"ats"),[f,setF]=useState(()=>({...defaults,...JSON.parse(localStorage.getItem("resumeData")||"{}")})),[generating,setGenerating]=useState(false);
 const save=()=>{localStorage.setItem("resumeData",JSON.stringify(f));localStorage.setItem("resumeTemplate",template);notify("Resume saved on this device")};
 const print=()=>{window.print()};
 const aiSummary=async()=>{setGenerating(true);try{const d=await api("/ai/chat",{method:"POST",body:JSON.stringify({message:`Improve my resume summary for a ${f.title} role. Current profile: ${f.summary}. Skills: ${f.skills}. Give one ATS-friendly 3-line summary without inventing experience.`})});setF({...f,summary:d.reply});notify("AI summary generated")}catch(e){notify(e.message,"err")}finally{setGenerating(false)}};
 return <><Title eyebrow="RESUME STUDIO" title="Canva-style Resume Builder" sub="Choose a template, edit your information, see the live preview, and print to PDF."><Button className="ghost" onClick={save}><I.Save/> Save</Button><Button className="ghost" onClick={aiSummary} loading={generating}><I.Sparkles/> AI improve</Button><Button className="primary" onClick={print}><I.Download/> Print / PDF</Button></Title><div className="templateStrip">{templates.map(t=><button className={template===t[1]?"templatePick active":"templatePick"} onClick={()=>setTemplate(t[1])} key={t[1]}><I.LayoutTemplate/><b>{t[0]}</b><span>Live preview</span></button>)}</div><div className="builderGrid"><div className="panel editor"><h3>Student information</h3><Form form={f} setForm={setF} fields={["name","title","email","phone","location","summary","skills","education","experience","projects","links"]}/><div className="tipBox"><I.Lightbulb/><span>Use measurable outcomes: “reduced processing time 30%” is stronger than “worked on processing.”</span></div></div><div className={"resumePreview "+template}><div className="resumeName">{f.name}</div><div className="resumeTitle">{f.title}</div><div className="resumeContact">{f.email} · {f.phone} · {f.location}</div>{["summary","skills","experience","projects","education","links"].map(k=><section className="resumeSection" key={k}><h4>{k.toUpperCase()}</h4><p>{f[k]}</p></section>)}</div></div></>
}
function Portfolio({notify}){
 const [p,setP]=useState([]),[show,setShow]=useState(false),[template,setTemplate]=useState("showcase"),[f,setF]=useState({title:"",description:"",tech_stack:"",project_url:"",image_url:""}),[busy,setBusy]=useState(false);
 useEffect(()=>{api("/portfolio").then(setP)},[]);
 const add=async()=>{setBusy(true);try{await api("/portfolio",{method:"POST",body:JSON.stringify(f)});setP(await api("/portfolio"));setF({title:"",description:"",tech_stack:"",project_url:"",image_url:""});setShow(false);notify("Project added")}catch(e){notify(e.message,"err")}finally{setBusy(false)}};
 const remove=async id=>{try{await api(`/portfolio/${id}`,{method:"DELETE"});setP(await api("/portfolio"));notify("Project removed")}catch(e){notify(e.message,"err")}};
 return <><Title eyebrow="PROOF OF WORK" title="Portfolio Studio" sub="Build a recruiter-ready portfolio with templates, project evidence and example content."><Button className="primary" onClick={()=>setShow(true)}><I.Plus/> Add project</Button></Title><div className="templateStrip">{[["Showcase","showcase"],["Minimal","minimal"],["Developer","developer"],["Creative","creative"]].map(t=><button className={template===t[1]?"templatePick active":"templatePick"} onClick={()=>setTemplate(t[1])} key={t[1]}><I.Palette/><b>{t[0]}</b><span>Preview</span></button>)}</div><div className={"portfolioHero "+template}><div><div className="eyebrow">{template.toUpperCase()} PORTFOLIO</div><h2>{localStorage.getItem("resumeData")?JSON.parse(localStorage.getItem("resumeData")).name:"Your Name"}</h2><p>Student · Developer · Problem Solver</p></div><div className="portfolioStats"><b>{p.length}</b><span>Projects</span></div></div><div className="projectGrid">{p.map(x=><div className={"projectCard "+template} key={x.id}><div className="projectVisual">{x.image_url?<img src={x.image_url} alt=""/>:<I.Sparkles/>}</div><div className="projectBody"><h3>{x.title}</h3><p>{x.description}</p><div className="skillTags">{x.tech_stack.split(",").filter(Boolean).map(s=><span key={s}>{s.trim()}</span>)}</div>{x.project_url&&<a href={x.project_url} target="_blank" rel="noreferrer">View project ↗</a>}<button className="dangerText" onClick={()=>remove(x.id)}>Delete</button></div></div>)}{!p.length&&<div className="empty"><I.Palette/><h3>Start with an example project</h3><p>Example: “AI Resume Matcher — React + FastAPI + Ollama — compares a resume to a job description and highlights missing skills.”</p></div>}</div>{show&&<Modal title="Add project" close={()=>setShow(false)}><Form form={f} setForm={setF} fields={["title","description","tech_stack","project_url","image_url"]}/><Button className="primary" onClick={add} loading={busy}>Save project</Button></Modal>}</>
}
function Learning({notify}){
 const platforms=[["Coursera","AI, data, software and business courses","https://www.coursera.org/courses?query=free"],["edX","University-backed learning","https://www.edx.org/learn"],["freeCodeCamp","Hands-on coding paths","https://www.freecodecamp.org/learn/"],["MIT OpenCourseWare","Free university materials","https://ocw.mit.edu/search/"],["Khan Academy","Computing and foundations","https://www.khanacademy.org/"],["Google Skillshop","Digital and product skills","https://skillshop.withgoogle.com/"]];
 const quizzes=[["AI & Data Basics",[["Which Python structure stores key-value pairs?",["List","Dictionary","Tuple","Set"],1],["What does SQL SELECT do?",["Deletes","Retrieves data","Compiles code","Sends email"],1]]],["Frontend Fundamentals",[["Which technology builds component UIs?",["React","MySQL","Ollama","SQL"],0],["Which language styles pages?",["Python","CSS","SQL","Bash"],1]]],["Career Readiness",[["What should be tailored to a job?",["Resume keywords and evidence","Password","Browser theme","Nothing"],0],["What makes a portfolio project strong?",["Context, contribution and outcome","Only a logo","Copied tutorial only","Empty repo"],0]]]];
 const [tab,setTab]=useState("learn"),[quiz,setQuiz]=useState(null),[ans,setAns]=useState({}),[score,setScore]=useState(null);
 const finish=()=>{let c=0;quiz[1].forEach((q,i)=>{if(+ans[i]===q[3])c++});setScore(Math.round(c/quiz[1].length*100));notify("Quiz completed")};
 return <><Title eyebrow="LEARN · PRACTICE · PROVE" title="Learning & Quiz Center" sub="Trusted learning platforms plus quick knowledge checks."><Button className={tab==="learn"?"primary":"ghost"} onClick={()=>setTab("learn")}><I.BookOpen/> Learn</Button><Button className={tab==="quiz"?"primary":"ghost"} onClick={()=>setTab("quiz")}><I.Target/> Quizzes</Button></Title>{tab==="learn"?<div className="cardGrid">{platforms.map(x=><div className="featureCard" key={x[0]}><div className="cardIcon"><I.GraduationCap/></div><h3>{x[0]}</h3><p>{x[1]}</p><a className="primary linkButton" href={x[2]} target="_blank" rel="noreferrer">Open platform <I.ExternalLink/></a></div>)}</div>:!quiz?<div className="cardGrid">{quizzes.map(q=><div className="featureCard" key={q[0]}><div className="cardIcon"><I.Target/></div><h3>{q[0]}</h3><p>{q[1].length} questions · instant score</p><Button className="primary" onClick={()=>{setQuiz(q);setAns({});setScore(null)}}>Start quiz <I.PlayCircle/></Button></div>)}</div>:<div className="panel quizPanel"><div className="panelHead"><h3>{quiz[0]}</h3><Button className="ghost" onClick={()=>setQuiz(null)}>Back</Button></div>{quiz[1].map((q,i)=><div className="quizQuestion" key={i}><b>{i+1}. {q[0]}</b>{q[1].map((o,j)=><label key={j}><input type="radio" name={"q"+i} onChange={()=>setAns({...ans,[i]:j})}/>{o}</label>)}</div>)}{score===null?<Button className="primary" onClick={finish}>Submit quiz</Button>:<div className="quizResult"><div className="scoreCircle">{score}%</div><h3>{score>=80?"Excellent!":"Keep practicing!"}</h3></div>}</div>}</>
}
function ATS({notify}){
 const [resume,setResume]=useState(""),[jd,setJd]=useState(""),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false);
 const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);try{const fd=new FormData();fd.append("file",file);const d=await api("/ats/upload",{method:"POST",body:fd});setResume(d.resume_text);notify("Resume uploaded and extracted")}catch(e){notify(e.message,"err")}finally{setUploading(false)}};
 const score=async()=>{if(!resume||!jd)return notify("Add both resume and job description","err");setBusy(true);try{setResult(await api("/ats/score",{method:"POST",body:JSON.stringify({resume_text:resume,job_description:jd})}));notify("ATS analysis complete")}catch(e){notify(e.message,"err")}finally{setBusy(false)}};
 return <><Title eyebrow="RESUME INTELLIGENCE" title="ATS Score Checker" sub="Upload a PDF/DOCX/TXT resume or paste it, compare it with a job description, and get AI-backed improvement guidance."/><div className="atsGrid"><div className="panel"><label className="uploadBox"><I.Upload/> <span>{uploading?"Extracting…":"Upload resume (PDF, DOCX or TXT)"}</span><input type="file" accept=".pdf,.docx,.txt" onChange={upload}/></label><label className="wideLabel">Resume text<textarea className="atsArea" value={resume} onChange={e=>setResume(e.target.value)} placeholder="Your extracted or pasted resume text…"/></label><label className="wideLabel">Target job description<textarea className="atsArea" value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste the exact job description…"/></label><Button className="primary" onClick={score} loading={busy}><I.SearchCode/> Analyze ATS</Button></div><div className="panel">{result?<><div className="scoreCircle big">{result.score}%</div><h3>{result.summary||"Resume-to-job match"}</h3><h4>Matched keywords</h4><div className="skillTags">{result.matched_keywords.map(x=><span key={x}>{x}</span>)}</div><h4>Missing keywords</h4><div className="skillTags missing">{result.missing_keywords.map(x=><span key={x}>{x}</span>)}</div><h4>Improvements</h4><ul>{(result.improvements||[result.tip]).map((x,i)=><li key={i}>{x}</li>)}</ul></>:<div className="empty"><I.SearchCode/><h3>Your analysis appears here</h3><p>Use the exact job description you plan to apply to.</p></div>}</div></div></>
}
function Mentors({user,notify}){
 const {data:m=[]}=useAsync(()=>api("/mentors"),[]);const [selected,setSelected]=useState(null),[message,setMessage]=useState("I would like guidance on my next career step."),[busy,setBusy]=useState(false);
 const request=async()=>{setBusy(true);try{await api("/mentors/request",{method:"POST",body:JSON.stringify({mentor_id:selected.id,message})});notify("Mentor request sent")}catch(e){notify(e.message,"err")}finally{setBusy(false)}};
 return <><Title eyebrow="HUMAN GUIDANCE" title="Mentor Network" sub="Explore experienced mentors and send a connection request with your goal."/><div className="mentorGrid">{m.map(x=><div className="mentor" key={x.id}><div className="mentorAvatar">{x.name[0]}</div><h3>{x.name}</h3><b>{x.company}</b><p>{x.expertise}</p><div className="rating">★ {x.rating} · {x.experience_years} yrs · {x.availability}</div>{user.role==="STUDENT"&&<Button className="primary" onClick={()=>setSelected(x)}>Request connection</Button>}</div>)}</div>{selected&&<Modal title={`Connect with ${selected.name}`} close={()=>setSelected(null)}><p>Tell the mentor what you want help with.</p><textarea value={message} onChange={e=>setMessage(e.target.value)}/><Button className="primary" onClick={request} loading={busy}>Send request</Button></Modal>}</>
}
function Tools({user,notify}){
 const [role,setRole]=useState("Software Developer"),[company,setCompany]=useState("Target Company"),[letter,setLetter]=useState(""),[busy,setBusy]=useState(false),[q,setQ]=useState("Tell me about yourself."),[a,setA]=useState(""),[feedback,setFeedback]=useState("");
 const gen=async()=>{setBusy(true);try{const d=await api("/ai/cover-letter",{method:"POST",body:JSON.stringify({role,company,resume:localStorage.getItem("resumeData")||""})});setLetter(d.reply);notify("Cover letter drafted")}catch(e){notify(e.message,"err")}finally{setBusy(false)}};
 const coach=async()=>{setBusy(true);try{const d=await api("/ai/interview-feedback",{method:"POST",body:JSON.stringify({role,question:q,answer:a})});setFeedback(d.reply);notify("Interview feedback ready")}catch(e){notify(e.message,"err")}finally{setBusy(false)}};
 return <><Title eyebrow="CAREER TOOLKIT" title="Career Tools" sub="Practical AI helpers for applications and interview preparation."/><div className="toolGrid"><div className="panel"><div className="cardIcon"><I.Mail/></div><h3>AI cover letter generator</h3><div className="formGrid"><label>Role<input value={role} onChange={e=>setRole(e.target.value)}/></label><label>Company<input value={company} onChange={e=>setCompany(e.target.value)}/></label></div><Button className="primary" onClick={gen} loading={busy}><I.Sparkles/> Draft with AI</Button>{letter&&<textarea className="letterBox" value={letter} onChange={e=>setLetter(e.target.value)}/>}</div><div className="panel"><div className="cardIcon"><I.Video/></div><h3>AI interview coach</h3><label>Question<input value={q} onChange={e=>setQ(e.target.value)}/></label><label>Your answer<textarea value={a} onChange={e=>setA(e.target.value)} placeholder="Write your answer using STAR…"/></label><Button className="primary" onClick={coach} loading={busy}><I.MessageCircle/> Get feedback</Button>{feedback&&<div className="aiFeedback">{feedback}</div>}</div><div className="panel"><div className="cardIcon"><I.CheckSquare/></div><h3>Career checklist</h3>{["Complete profile","Add 5 relevant skills","Take a role-specific assessment","Build 2–3 portfolio projects","Create an ATS-ready resume","Practice 3 interview answers","Apply and track opportunities"].map(x=><div className="checkLine" key={x}><I.Check/>{x}</div>)}</div></div></>
}
function Applications(){const {data:a=[],loading}=useAsync(()=>api('/applications'),[]);const [insight,setInsight]=useState(null);const analyze=async id=>{try{setInsight(await api('/innovation/rejection-learning/'+id,{method:'POST'}))}catch(e){setInsight({error:e.message})}};if(loading)return <Loading/>;return <><Title eyebrow="PIPELINE" title="My Applications" sub="Track applications and turn rejection into a concrete learning plan."/><div className="panel tablePanel"><table><thead><tr><th>Role</th><th>Company</th><th>Type</th><th>Status</th><th>Date</th><th>Learning</th></tr></thead><tbody>{a.map(x=><tr key={x.id}><td><b>{x.title}</b></td><td>{x.company}</td><td>{x.kind}</td><td><span className="status">{x.status}</span></td><td>{new Date(x.applied_at).toLocaleDateString()}</td><td>{x.status==='REJECTED'&&<Button className="ghost small" onClick={()=>analyze(x.id)}>Analyze rejection <I.Sparkles/></Button>}</td></tr>)}</tbody></table>{!a.length&&<div className="empty">No applications yet.</div>}</div>{insight&&<div className="panel" style={{marginTop:20}}><div className="eyebrow">REJECTION → LEARNING</div><h3>What to improve next</h3><p>{(insight.likely_reasons||[]).join(' · ')}</p>{(insight.learning_actions||[]).map(x=><div className="listItem" key={x}><I.Target/>{x}</div>)}</div>}</>}

function Profile({user,setUser,notify}){const [f,setF]=useState({name:user.name,headline:user.headline||"",location:user.location||"",phone:user.phone||"",bio:user.bio||""}),[busy,setBusy]=useState(false);const save=async()=>{setBusy(true);try{const u=await api("/profile",{method:"PUT",body:JSON.stringify(f)});localStorage.setItem("user",JSON.stringify(u));setUser(u);notify("Profile saved")}catch(e){notify(e.message,"err")}finally{setBusy(false)}};return <><Title eyebrow="IDENTITY" title="My Profile" sub="Keep your student or professional identity recruiter-ready."><Button className="primary" onClick={save} loading={busy}>Save changes</Button></Title><div className="profilePanel"><div className="bigAvatar">{f.name?.[0]}</div><div className="profileForm"><Form form={f} setForm={setF} fields={["name","headline","location","phone","bio"]}/><div className="tipBox"><I.ShieldCheck/><span>Your account uses a hashed password and a signed session token.</span></div></div></div></>}
function Industry({user,notify}){const {data:apps=[]}=useAsync(()=>api('/recruiter/applications'),[]);const {data:talent=[]}=useAsync(()=>api('/industry/talent'),[]);const [status,setStatus]=useState('REVIEW');const update=async id=>{try{await api(`/applications/${id}/${status}`,{method:'PATCH'});notify('Candidate status updated')}catch(e){notify(e.message,'err')}};return <><Title eyebrow="ACADEMIA ↔ INDUSTRY" title="Industry Hub" sub="Find talent, publish opportunities and manage the applicant pipeline."/><div className="grid2"><div className="panel"><h3>AI Talent Finder</h3>{talent.slice(0,6).map(x=><div className="listItem" key={x.id}><I.UserRound/><div><b>{x.name}</b><p>{x.headline||'Career explorer'} · {x.location||'Location not set'}</p><div className="skillTags">{x.skills.slice(0,5).map(s=><span key={s}>{s}</span>)}</div></div><strong>{x.score}</strong></div>)}</div><div className="panel"><h3>Recruiting workflow</h3><p>Use Jobs to publish a role, then move candidates through review, interview, shortlist, offer or rejection.</p><Button className="primary" onClick={()=>notify('Open Jobs to publish a role')}>Publish opportunity <I.BriefcaseBusiness/></Button></div></div><div className="panel tablePanel"><h3>Candidate applications</h3><div className="statusControl"><select value={status} onChange={e=>setStatus(e.target.value)}><option>REVIEW</option><option>INTERVIEW</option><option>SHORTLISTED</option><option>OFFER</option><option>REJECTED</option></select></div><table><thead><tr><th>Student</th><th>Role</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody>{apps.map(x=><tr key={x.id}><td><b>{x.student.name}</b><small>{x.student.headline}</small></td><td>{x.role}</td><td>{x.student.email}</td><td>{x.status}</td><td><Button className="ghost small" onClick={()=>update(x.id)}>Set {status}</Button></td></tr>)}</tbody></table>{!apps.length&&<div className="empty">No applications for your opportunities yet.</div>}</div></>}

function Admin(){const {data:a,loading,error}=useAsync(()=>api('/admin/overview'),[]);if(loading)return <Loading/>;if(error)return <ErrorBox text={error}/>;return <><Title eyebrow="CONTROL CENTER" title="Admin Analytics" sub="Live platform-wide counts from the production database."/><div className="statGrid">{Object.entries(a).map(([k,v])=><div className="stat" key={k}><b>{v}</b><small>{k.replaceAll('_',' ')}</small></div>)}</div><div className="panel"><h3>Platform health</h3>{[['Authentication','Accounts and roles stored in MySQL/TiDB'],['AI intelligence','Ollama-powered career features'],['Opportunity engine','Jobs, internships and matching'],['Academia bridge','Institution demand and curriculum translation'],['Industry workflow','Talent discovery and application pipeline']].map(x=><div className="moduleLine" key={x[0]}><I.CheckCircle2/> <div><b>{x[0]}</b><small>{x[1]}</small></div><span>Active</span></div>)}</div></>}

function SectionCards({items}){return <div className="cardGrid three">{items.map(([Icon,title,text])=><div className="featureCard innovationCard" key={title}><div className="cardIcon"><Icon/></div><h3>{title}</h3><p>{text}</p></div>)}</div>}
function CareerDNA({go}){const {data:d,loading,error}=useAsync(()=>api("/innovation/career-dna"),[]);if(loading)return <Loading/>;if(error)return <ErrorBox text={error}/>;return <><Title eyebrow="CAREER IDENTITY ENGINE" title="Career DNA" sub="Your capability fingerprint is calculated from skills, projects and assessment evidence."><Button className="primary" onClick={()=>go("Career Twin")}>Ask Career Twin <I.Bot/></Button></Title><div className="cardGrid three">{Object.entries(d.scores).map(([k,v])=><div className="featureCard" key={k}><div className="scoreCircle">{v}</div><h3>{k}</h3><div className="bar"><i style={{width:v+"%"}}/></div></div>)}</div><div className="grid2"><div className="panel"><div className="eyebrow">ARCHETYPE</div><h2>{d.archetype}</h2><p>Your profile signals are translated into practical career strengths—not personality labels.</p></div><div className="panel"><h3>Next actions</h3>{d.next_actions.map(x=><div className="listItem" key={x}><I.CheckCircle2/>{x}</div>)}</div></div></>}

function FutureSelf(){const [years,setYears]=useState(3),[d,setD]=useState(null),[loading,setLoading]=useState(false);const run=async()=>{setLoading(true);try{setD(await api("/innovation/future-self",{method:"POST",body:JSON.stringify({years})}))}finally{setLoading(false)}};useEffect(()=>{run()},[years]);return <><Title eyebrow="FUTURE SIMULATOR" title="Future Self" sub="Compare realistic career scenarios generated from your current evidence."/><div className="panel"><label className="wideLabel">Simulation horizon: {years} years<input type="range" min="1" max="5" value={years} onChange={e=>setYears(+e.target.value)}/></label></div>{loading?<Loading/>:d&&<div className="cardGrid three">{d.paths.map(p=><div className="featureCard" key={p.title}><div className="scoreCircle">{p.fit_score}</div><h3>{p.title}</h3><p><b>{years}-year scenario</b></p><div className="learnSteps">{(p.milestones||[]).map(x=><span key={x}>{x}</span>)}</div><Button className="ghost">View risks <I.ArrowRight/></Button></div>)}</div>}</>}

function CareerLab({notify}){const [role,setRole]=useState('Data Analyst'),[answer,setAnswer]=useState(''),[result,setResult]=useState(null),[loading,setLoading]=useState(false);const submit=async()=>{setLoading(true);try{const d=await api('/innovation/career-lab',{method:'POST',body:JSON.stringify({role,answer})});setResult(d);notify('Career experiment evaluated')}catch(e){notify(e.message,'err')}finally{setLoading(false)}};return <><Title eyebrow="TRY BEFORE YOU CHOOSE" title="Career Experiment Lab" sub="Test the kind of thinking the role requires, then get AI feedback."/><div className="panel"><div className="filters"><select value={role} onChange={e=>setRole(e.target.value)}><option>Data Analyst</option><option>Software Developer</option><option>Product Manager</option><option>UX Designer</option></select></div><h3>Mini challenge</h3><p>A retail team sees weekend sales rise 35% while returns also rise. What would you investigate first, and why?</p><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Explain your first step and reasoning…"/><Button className="primary" onClick={submit} loading={loading}>Evaluate experiment <I.Sparkles/></Button>{result&&<div className="quizResult"><div className="scoreCircle">{result.score}</div><div><h3>Career Fit Signal: {result.score}%</h3><p>{result.feedback}</p><b>Next challenge:</b> {result.next_challenge}</div></div>}</div></>}

function ProjectBuilder({notify}){const [role,setRole]=useState('Data Analyst'),[idea,setIdea]=useState(''),[plan,setPlan]=useState(null),[loading,setLoading]=useState(false);const build=async()=>{setLoading(true);try{setPlan(await api('/innovation/project-builder',{method:'POST',body:JSON.stringify({role,idea})}));notify('AI project blueprint created')}catch(e){notify(e.message,'err')}finally{setLoading(false)}};return <><Title eyebrow="PROJECT BUILDER LAB" title="Build Proof, Not Just Skills" sub="Generate a portfolio-ready project from your target role and current evidence."><Button className="primary" onClick={build} loading={loading}>Generate blueprint <I.Sparkles/></Button></Title><div className="panel formGrid"><label>Target role<select value={role} onChange={e=>setRole(e.target.value)}><option>Data Analyst</option><option>Software Developer</option><option>AI Engineer</option><option>Product Manager</option></select></label><label>Project idea<input value={idea} onChange={e=>setIdea(e.target.value)} placeholder="e.g. campus placement analytics"/></label></div>{plan&&<div className="resultHero"><div className="cardIcon"><I.Hammer/></div><div><div className="eyebrow">AI-GENERATED BLUEPRINT</div><h2>{plan.title}</h2><p>{plan.problem}</p><p><b>Stack:</b> {(plan.stack||[]).join(' · ')}</p><div className="learnSteps">{(plan.milestones||[]).map((s,i)=><span key={s}>{i+1}. {s}</span>)}</div><p><b>Success metrics:</b> {(plan.metrics||[]).join(', ')}</p><p><b>Portfolio evidence:</b> {(plan.portfolio_evidence||[]).join(', ')}</p></div></div>}</>}

function JobMatch(){const {data=[],loading,error}=useAsync(()=>api('/innovation/job-match'),[]);if(loading)return <Loading/>;if(error)return <ErrorBox text={error}/>;return <><Title eyebrow="AI TALENT MATCH" title="Job Match AI" sub="Matches are calculated against the skills currently stored in your profile."/><div className="oppGrid">{data.map(j=><div className="oppCard" key={j.id}><div className="oppTop"><span className="tag">AI MATCH</span><b>{j.score}%</b></div><h3>{j.title}</h3><p>{j.company} · {j.location}</p><div className="skillTags">{j.matched.map(x=><span key={x}>✓ {x}</span>)}{j.missing.slice(0,4).map(x=><span key={x}>Gap: {x}</span>)}</div><Button className="primary small">Review opportunity <I.ChevronRight/></Button></div>)}</div></>}

function OpportunityRadar(){const {data,loading,error}=useAsync(()=>api('/innovation/radar'),[]);if(loading)return <Loading/>;if(error)return <ErrorBox text={error}/>;return <><Title eyebrow="PERSONAL OPPORTUNITY INTELLIGENCE" title="Opportunity Radar" sub="Prioritized opportunities based on your live profile and open roles."/><div className="cardGrid three">{(data.alerts||[]).map(x=><div className="featureCard radarCard" key={x.id}><div className="eyebrow">{x.priority} PRIORITY</div><div className="scoreCircle">{x.score}%</div><h3>{x.title}</h3><p>{x.company}</p><p>{x.reason}</p><div className="skillTags">{x.missing.slice(0,3).map(s=><span key={s}>Learn {s}</span>)}</div></div>)}</div></>}

function CareerMirror(){const [role,setRole]=useState('Data Analyst');const {data,loading,error}=useAsync(()=>api('/innovation/career-mirror?target_role='+encodeURIComponent(role)),[role]);if(loading)return <Loading/>;if(error)return <ErrorBox text={error}/>;return <><Title eyebrow="NOW ↔ TARGET" title="Career Mirror" sub="Compare your stored evidence with skills demanded by real open opportunities."><select value={role} onChange={e=>setRole(e.target.value)}><option>Data Analyst</option><option>Software Developer</option><option>AI Engineer</option></select></Title><div className="panel">{data.skills.map(x=><div className="gapRow" key={x.skill}><div><b>{x.skill}</b><span>Level {x.current}/4 → {x.target}/4</span></div><div className="bar"><i style={{width:(x.current/4*100)+'%'}}/></div><strong>{x.gap?'Gap '+x.gap:'Ready'}</strong></div>)}</div></>}

function SkillGraph(){const [role,setRole]=useState('Data Analyst');const {data,loading,error}=useAsync(()=>api('/innovation/skill-graph?target_role='+encodeURIComponent(role)),[role]);if(loading)return <Loading/>;if(error)return <ErrorBox text={error}/>;return <><Title eyebrow="INTERACTIVE LEARNING INTELLIGENCE" title="Skill Dependency Graph" sub="A dynamic learning sequence based on your target role and current skills."><select value={role} onChange={e=>setRole(e.target.value)}><option>Data Analyst</option><option>Software Developer</option><option>AI Engineer</option></select></Title><div className="skillGraph">{data.nodes.map((n,i)=><div className="graphNode" key={n.name}><div className="scoreCircle">{n.level||0}</div><b>{n.name}</b><small>{n.status}</small>{i<data.nodes.length-1&&<I.ChevronDown/>}</div>)}</div></>}

function CareerTwin(){const [q,setQ]=useState('Would I qualify for a Data Analyst internship?'),[ans,setAns]=useState(null),[loading,setLoading]=useState(false);const ask=async()=>{setLoading(true);try{setAns(await api('/innovation/career-twin',{method:'POST',body:JSON.stringify({question:q})}))}catch(e){setAns({answer:e.message,readiness:0})}finally{setLoading(false)}};return <><Title eyebrow="DIGITAL CAREER TWIN" title="Career Twin" sub="Ask an evidence-based version of your professional profile."><Button className="primary" onClick={ask} loading={loading}>Ask my Twin <I.Bot/></Button></Title><div className="panel twin"><div className="aiLogo"><I.Bot/></div><div><h3>Evidence-based career answers</h3><input value={q} onChange={e=>setQ(e.target.value)}/>{ans&&<div className="aiFeedback"><b>Readiness: {ans.readiness}%</b><p>{ans.answer}</p><b>Evidence</b>{(ans.evidence||[]).map(x=><div key={x}>{x}</div>)}<b>Actions</b>{(ans.actions||[]).map(x=><div key={x}>• {x}</div>)}</div>}</div></div></>}

function GrowthSimulator(){const [project,setProject]=useState(0),[intern,setIntern]=useState(0),[interview,setInterview]=useState(0),[d,setD]=useState(null);useEffect(()=>{api('/innovation/growth-simulator',{method:'POST',body:JSON.stringify({projects:project,internships:intern,interviews:interview})}).then(setD)},[project,intern,interview]);return <><Title eyebrow="CAREER STRATEGY" title="Growth Simulator" sub="Simulate how evidence-building actions could change your readiness score."/><div className="grid2"><div className="panel"><label className="wideLabel">Portfolio projects: {project}<input type="range" min="0" max="4" value={project} onChange={e=>setProject(+e.target.value)}/></label><label className="wideLabel">Internship experience: {intern}<input type="range" min="0" max="1" value={intern} onChange={e=>setIntern(+e.target.value)}/></label><label className="wideLabel">Interview practice: {interview}<input type="range" min="0" max="4" value={interview} onChange={e=>setInterview(+e.target.value)}/></label></div>{d&&<div className="resultHero"><div className="scoreCircle big">{d.simulated}</div><div><div className="eyebrow">SIMULATED READINESS</div><h2>{d.simulated}%</h2><p>Change from current evidence: +{d.delta} points.</p><b>{d.recommendation}</b></div></div>}</div></>}

function Institution({notify}){const {data:d,loading,error}=useAsync(()=>api('/institution/overview'),[]);const [cur,setCur]=useState(null),[loadingCur,setLoadingCur]=useState(false);const translate=async()=>{setLoadingCur(true);try{setCur(await api('/institution/curriculum-translator'))}catch(e){notify(e.message,'err')}finally{setLoadingCur(false)}};if(loading)return <Loading/>;if(error)return <ErrorBox text={error}/>;return <><Title eyebrow="ACADEMIA INTELLIGENCE" title="Institution Hub" sub="Live institution metrics and AI curriculum intelligence."><Button className="primary" onClick={translate} loading={loadingCur}>Generate curriculum insight <I.Sparkles/></Button></Title><div className="statGrid"><div className="stat"><b>{d.students}</b><small>students</small></div><div className="stat"><b>{d.applications}</b><small>applications</small></div><div className="stat"><b>{d.open_opportunities}</b><small>open opportunities</small></div><div className="stat"><b>{d.assessment_attempts}</b><small>assessment attempts</small></div></div><div className="grid2"><div className="panel"><h3>Demand signals</h3>{d.top_skills.map(x=><div className="gapRow" key={x.skill}><b>{x.skill}</b><div className="bar"><i style={{width:Math.min(100,x.holders*15+20)+'%'}}/></div><strong>{x.holders}</strong></div>)}</div><div className="panel"><h3>Institution actions</h3><div className="listItem"><I.Users/> Identify students who need targeted support</div><div className="listItem"><I.BriefcaseBusiness/> Coordinate placement opportunities</div><div className="listItem"><I.BookOpen/> Translate employer demand into curriculum modules</div></div></div>{cur&&<div className="panel" style={{marginTop:20}}><div className="eyebrow">AI CURRICULUM TRANSLATOR</div><h3>Priority skills</h3><div className="skillTags">{cur.priority_skills.map(x=><span key={x}>{x}</span>)}</div><h3>Recommended modules</h3>{cur.modules.map((m,i)=><div className="listItem" key={i}><I.CheckCircle2/><div><b>{m.name}</b><p>{m.reason}</p><small>Activities: {(m.activities||[]).join(', ')}</small></div></div>)}</div>}</>}

function Form({form,setForm,fields}){return <div className="formGrid">{fields.map(k=><label key={k}>{k.replaceAll("_"," ")}{["description","bio","summary","skills","education","experience","projects","links"].includes(k)?<textarea value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})}/>:<input value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>)}</div>}
function Modal({title,close,children}){return <div className="modalBack"><div className="modal"><div className="modalHead"><h3>{title}</h3><button className="icon" onClick={close}><I.X/></button></div>{children}</div></div>}
createRoot(document.getElementById("root")).render(<BrowserRouter><App/></BrowserRouter>);
